Add es domain encryption support
ministryofjustice/cloud-platform-terraform-elasticsearch pull request #14
Opened 2020-11-30 10:15 UTC by garethmdavies

Attempt to add encryption support to ES domain. Consideration: should the encryption be enabled by default?

2020-11-30 10:32 UTC, mattops commented on main.tf
> +  count       = var.encryption_at_rest == "true" || var.node_to_node_encryption_enabled == "true" ? 1 : 0
Do you need the 
```
|| var.node_to_node_encryption_enabled == "true"
```
Not sure that node_to_node_encryption requires the KMS key.

2021-01-21 16:23 UTC, mogaal requested changes

2021-01-21 16:23 UTC, mogaal commented on variables.tf
> +  type        = string
Hi. Thanks for your contribution. Can you please change this to type bool, terraform support bool type.

2021-01-21 16:23 UTC, mogaal commented on main.tf
> +  count       = var.encryption_at_rest == "true" ? 1 : 0
Once you change variable type to `bool` this can be written like

```
  count       = var.encryption_at_rest ? 1 : 0
```

2021-01-21 16:23 UTC, mogaal commented on main.tf
> +  count       = var.encryption_at_rest == "true" ? 1 : 0
Same here, once you change variable type to `bool` this can be written like

```
  count       = var.encryption_at_rest ? 1 : 0
```

2021-01-21 16:23 UTC, mogaal commented on main.tf
> +    kms_key_id = var.encryption_at_rest == "true" ? aws_kms_key.kms[0].arn : null
Also here.

2021-01-21 16:45 UTC, mogaal approved these changes

2021-01-22 10:14 UTC, merged