Update the es module for es_proxy works with IRSA.
ministryofjustice/cloud-platform-terraform-elasticsearch pull request #22
Opened 2021-06-04 09:02 UTC by vijay-veeranki

Update the es module:
For es_proxy works with IRSA.
Create separate .tf files for irsa, assume and proxy deployment
Get the oidc_issuer_url from the state file(this needs replacing as a data resource for eks cluster is WIP).

2021-06-08 15:04 UTC, razvan-moj requested changes

2021-06-08 15:04 UTC, razvan-moj commented on README.md
> +| isra_enabled | This will enable to use IRSA instead of KIAM | bool | false | no |
typo: irsa

2021-06-08 15:04 UTC, razvan-moj commented on README.md
> +| assume_enabled | This will enable to use KIAM instead of ISRA | bool | true | no |
same typo (you might want to generate this block using tfdocs?)

2021-06-09 10:30 UTC, vijay-veeranki commented
@razvan-moj Thanks for the review, updated it now, can you review it again please

2021-06-09 10:44 UTC, razvan-moj approved these changes

2021-06-09 10:49 UTC, merged